FROM node:16 AS build
WORKDIR /app
COPY package*.json ./
RUN npm install
RUN npm install -g @angular/cli
COPY . .
RUN ng build --configuration=docker --output-path=dist/bookappclient

FROM nginx:latest
COPY --from=build /app/dist/bookappclient /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
